### ISSUE TITLE
API: Compare-and-swap

### ISSUE THREAD

**Issue by jgarzik** [jgarzik/gdbm-native-rs#33]
It is feasible to support a compare-and-swap API, a la sled's:
```
// Atomic compare-and-swap.
db.compare_and_swap(
    b"yo!",      // key
    Some(b"v1"), // old value, None for not present
    Some(b"v2"), // new value, None for delete
)
.unwrap();
```

**Comment by drystone** [comment]
Isn't `compare_and_swap` really only useful in avoiding race conditions? If we were to implement concurrent writes it may be useful, but otherwise it's confusing and adds bloat.

**Comment by jgarzik** [comment]
Explored in #88 - let's leave it out for now
